"""create initial database models

Revision ID: d25daba5ef6b
Revises: 
Create Date: 2026-09-11 11:36:20.009151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd25daba5ef6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_source_type'), 'documents', ['source_type'], unique=False)
    op.create_table('document_versions',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('document_id', 'version_number')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_hash', sa.String(length=64), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('has_ocr', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id'),
    sa.UniqueConstraint('version_id', 'page_number')
    )
    op.create_index(op.f('ix_document_pages_version_id'), 'document_pages', ['version_id'], unique=False)
    op.create_table('document_images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('image_number', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('image_ext', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('vision_summary', sa.Text(), nullable=True),
    sa.Column('surrounding_context', sa.Text(), nullable=True),
    sa.Column('embedding_status', sa.Enum('pending', 'embedded', 'failed', 'stale', name='embedding_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.page_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_document_images_document_id'), 'document_images', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_images_page_id'), 'document_images', ['page_id'], unique=False)
    op.create_index(op.f('ix_document_images_version_id'), 'document_images', ['version_id'], unique=False)
    op.create_table('document_tables',
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('surrounding_context', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('table_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding_status', sa.Enum('pending', 'embedded', 'failed', 'stale', name='embedding_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.page_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_index(op.f('ix_document_tables_content_hash'), 'document_tables', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_tables_document_id'), 'document_tables', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_tables_page_id'), 'document_tables', ['page_id'], unique=False)
    op.create_index(op.f('ix_document_tables_version_id'), 'document_tables', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_tables_version_id'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_page_id'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_document_id'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_content_hash'), table_name='document_tables')
    op.drop_table('document_tables')
    op.drop_index(op.f('ix_document_images_version_id'), table_name='document_images')
    op.drop_index(op.f('ix_document_images_page_id'), table_name='document_images')
    op.drop_index(op.f('ix_document_images_document_id'), table_name='document_images')
    op.drop_table('document_images')
    op.drop_index(op.f('ix_document_pages_version_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_source_type'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
