"""add storage keys, embedding status, page text columns

Revision ID: daf696bca684
Revises: d25daba5ef6b
Create Date: 2026-09-25 11:18:17.381870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daf696bca684'
down_revision: Union[str, Sequence[str], None] = 'd25daba5ef6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_images', sa.Column('image_object_key', sa.String(length=500), nullable=True))
    op.drop_column('document_images', 'object_key')
    op.add_column('document_pages', sa.Column('page_object_key', sa.String(length=500), nullable=True))
    op.add_column('document_pages', sa.Column('page_text', sa.Text(), nullable=True))
    op.add_column('document_pages', sa.Column('page_ocr_text', sa.Text(), nullable=True))
    op.add_column('document_pages', sa.Column('embedding_status', sa.Enum('pending', 'embedded', 'failed', 'stale', name='embedding_status_enum'), nullable=False))
    op.add_column('document_tables', sa.Column('table_object_key', sa.String(length=500), nullable=True))
    op.alter_column('document_tables', 'table_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('document_tables', 'normalized_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('document_versions', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('document_versions', sa.Column('document_object_key', sa.String(length=500), nullable=False))
    op.add_column('document_versions', sa.Column('embedding_status', sa.Enum('pending', 'embedded', 'failed', 'stale', name='embedding_status_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'embedding_status')
    op.drop_column('document_versions', 'document_object_key')
    op.drop_column('document_versions', 'summary')
    op.alter_column('document_tables', 'normalized_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('document_tables', 'table_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('document_tables', 'table_object_key')
    op.drop_column('document_pages', 'embedding_status')
    op.drop_column('document_pages', 'page_ocr_text')
    op.drop_column('document_pages', 'page_text')
    op.drop_column('document_pages', 'page_object_key')
    op.add_column('document_images', sa.Column('object_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('document_images', 'image_object_key')
    # ### end Alembic commands ###
